name: ReactJS CI/CD Example

on:
  pull_request:
  push:
    branches:
    - master

jobs:
  build:
    name: Setup
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install yarn
      - run: yarn
      - run: yarn build
      - uses: actions/upload-artifact@v2
        with:
          name: Deploy
          path: ./build
      
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/download-artifact@v2
        with:
          name: Deploy
          path: ./build
      - run: npm install --global surge
      - run: surge ./build ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
